# Site settings
title: "Vitor Nogueira"
description: "Personal resume website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
  
# Resume settings
resume_avatar: true
resume_name: "vitornogueira"
resume_title: "Fullstack developer"
# resume_contact_email: "rnogueira.vitor@gmail.com"
# resume_contact_telephone: ""
# resume_contact_address: ""
# resume_header_contact_info: ""
# resume_header_intro: ""

resume_looking_for_work: "yes"

resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
resume_section_interests: true

resume_social_links:
  resume_github_url: "https://github.com/nogueivi"
  resume_linkedin_url: "https://www.linkedin.com/in/nogueira-vitor"
  resume_website_url: "http://nogueivi.github.io"
  
resume_theme: default
